In [1]:
import matplotlib
print matplotlib.__version__, matplotlib.__file__

1.5.1 C:\Anaconda\lib\site-packages\matplotlib\__init__.pyc


In [1]:
import numpy as np
import quaternionarray as qa
import amcmorl_py_tools.vecgeom as vg
import amcmorl_py_tools.vectors as ve
from amcmorl_py_tools.vecgeom import transformations as tf

C:\Users\amcmorl\Documents\python-lib\amcmorl_py_tools\vectors.py:5: UserWarning: This module is deprecated. Use vecgeom package instead.
  warn("This module is deprecated. Use vecgeom package instead.")


In [4]:
vmk1 = np.array([-286, 175, -2145])
qmk1 = qa.norm(np.array([-0.005, 0.21, -0.898, 0.386]))
vpl1 = np.array([-127, 178, -2131])
qpl1 = qa.norm(np.array([0.254, -.026, -0.965, 0.054]))
vmk2 = np.array([-244.5, 281.9, -2124.1])
qmk2 = qa.norm(np.array([-0.254, -0.124, -0.532, 0.798]))
vpl2 = np.array([-178.1, 27.3, -2158])
qpl2 = qa.norm(np.array([0.20, -0.163, -0.774, 0.577]))

In [45]:
Qplr = qa.mult(qpl2, qa.inv(qpl1))
Qmkr = qa.mult(qmk2, qa.inv(qmk1))

In [38]:
tf.DCM2quat(ve.rotmat_between_two_vecs(vpl1, vpl2))

array([-0.03515595,  0.01137522,  0.00304533,  0.99931246])

In [39]:
Qplr

array([[ 0.29483757, -0.02742871, -0.56298821, -0.77159753]])

In [46]:
ipl =qa.mult(qa.inv(qpl1), qa.inv(Qplr))
iplck = qa.inv(qpl2) 

In [47]:
ipl

array([[-0.20014275,  0.16311634,  0.77455245,  0.57741184]])

In [48]:
iplck

array([-0.20014275,  0.16311634,  0.77455245,  0.57741184])

In [49]:
imk = qa.mult(qa.inv(qmk1), qa.inv(Qmkr))
imkck = qa.inv(qmk2)

In [50]:
imk

array([[ 0.25403557,  0.12401736,  0.5320745 ,  0.79811174]])

In [51]:
imkck

array([ 0.25403557,  0.12401736,  0.5320745 ,  0.79811174])

In [23]:
vmk3 = np.array([-339.6, 252, -2180])
qmk3 = qa.norm(np.array([0.02, 0.25, -0.916, 0.310]))
vpl3 = np.array([-224, 35, -2185])
qpl3 = qa.norm(np.array([0.26, -0.05, -0.953, 0.161]))

In [52]:
Qplr2 = qa.mult(qpl3, qa.inv(qpl2))
Qmkr2 = qa.mult(qmk3, qa.inv(qmk2))

In [53]:
ipl2 = qa.mult(qa.inv(qpl2), qa.inv(Qplr2))
iplck2 = qa.inv(qpl3)

In [54]:
ipl2

array([[-0.25945184,  0.04989458,  0.95099078,  0.16066056]])

In [55]:
iplck2

array([-0.25945184,  0.04989458,  0.95099078,  0.16066056])

Qc = Quaternion of plate at on off calibration

P1 = Position of plate before moving 70mm

P2 = Poistion of plate after moving 70mm

Pf = P2- P1

Qmkc = Coil marker quaternion at calibration time

Ppl = Plate position at calibration time

Qmkt = Coil marker quaternion at trial time

r = Rotation between coil marker orientation at calibration tiem and trial time

vclt = Vector Pf after coil rotation = Current direction

Add vclc to the coil position calculated to get position of vector head and use matplotlib 3D to plot a quiver

In [12]:
Qc = np.array([0.00, 0.00, 0.00, -1.00])
P1 = np.array([-224, 35, -2185])
P2 = np.array([-224, 115, -2185])
Pf = np.array([0, 70, 0])

In [19]:
Qmkc = qa.norm(tf.eul2quat(np.array([0, 0, 0]), 'xyz'))
Qmkt = qa.norm(tf.eul2quat(np.array([0, 0, np.radians(90)]), 'xyz'))

In [21]:
r = qa.mult(Qmkt, qa.inv(Qmkc))
vclt = qa.rotate(r, Pf)
#Qmkt = qa.mult(Qr, Qmkc)

In [22]:
vclt

array([[ -7.00000000e+01,   1.42108547e-14,   0.00000000e+00]])

In [7]:
Qr = qa.mult(Qc, qa.inv(Qmkc))
Qclt = qa.mult(Qmkt, Qr)

In [8]:
Qclt

array([[ 0.36625584,  0.11362637, -0.78289207,  0.48793618]])

In [11]:
qa.mult(Qclt, qa.inv(Qr))

array([[-0.00499147,  0.20964156, -0.89646722,  0.38534115]])

In [12]:
Qmkt

array([-0.00500119,  0.21004989, -0.89821335,  0.38609171])

In [13]:
Qr

array([[ 0.20623427,  0.27427053,  0.21350292,  0.91362772]])

In [4]:
Qpl = qa.norm(np.array([0.254, -.026, -0.965, 0.054]))
P3 =  np.array([-2, 35, -2149])
P4 = P3 + Pf

In [ ]:
Qr = qa.mult(Qc, qa.inv(qa.mult(Qmkc, Qpl)))
Qclt = qa.mult(Qmkt, Qr)

In [31]:
tf.axang2quat(np.array([0,0,0]))

array([ 0.,  0.,  0.,  1.])

In [ ]:
vector = np.array([1.6, 85.4, 2.4])
ori = np.array([0.00, 0.00, 0.00, -1.00])